[package]
name = "milkapis_client_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12.1"
tonic-web = "0.10.2"
tonic-health = "0.10.2"
tonic-web-wasm-client = "0.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tonic = { version = "0.10.2", features = ["tls", "gzip"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic = { version = "0.10.2", default-features = false }

[target.'cfg(target_arch = "wasm32")'.build-dependencies]
tonic-build = { version = "0.10.2", default-features = false, features = [
    "prost",
] }

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
tonic-build = "0.10.2"
