[package]
name = "milkapis_client_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { version = "0.10.2", features = ["tls", "gzip"] }
prost = "0.12.1"
tonic-web = "0.10.2"
tonic-health = "0.10.2"

[build-dependencies]
tonic-build = "0.10.2"
