[package]
name = "milkapis_client_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12.3"
tonic-web = "0.11.0"
tonic-health = "0.11.0"
tonic-web-wasm-client = "0.5.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tonic = { version = "0.11.0", features = ["tls", "gzip"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic = { version = "0.11.0", default-features = false, features = [
    "prost",
    "codegen",
    "gzip",
] }

[target.'cfg(target_arch = "wasm32")'.build-dependencies]
tonic-build = { version = "0.11.0", default-features = false, features = [
    "prost",
] }

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
tonic-build = "0.11.0"
