name: milkapis_client_dart
description: A starting point for Dart libraries or applications.
version: 0.0.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0-190.0.dev

# Add regular dependencies here.
dependencies:
  fixnum: ^1.1.0
  grpc: ^3.2.4
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
